# Generated by Django 4.1.1 on 2022-10-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signuplogin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="myposts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("desc", models.TextField()),
                ("photo", models.TextField()),
            ],
        ),
    ]
