# Generated by Django 4.1.1 on 2022-10-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signuplogin", "0002_myposts"),
    ]

    operations = [
        migrations.RenameModel(old_name="myposts", new_name="mypost",),
    ]
