# Generated by Django 4.1.1 on 2023-02-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signuplogin", "0004_mystory"),
    ]

    operations = [
        migrations.CreateModel(
            name="posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("mind", models.TextField()),
                ("img", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.TextField()),
                ("lastname", models.TextField()),
                ("email", models.TextField()),
                ("password", models.TextField()),
            ],
        ),
        migrations.DeleteModel(name="mypost",),
        migrations.DeleteModel(name="mystory",),
        migrations.DeleteModel(name="myusers",),
    ]
